categories:
  sourceopt:
    label: 'SourceOpt[imization]'
  sourceopt.cleaner:
    label: 'Cleaner'
    parent: sourceopt
  sourceopt.formater:
    label: 'Formater'
    parent: sourceopt
  sourceopt.svgstore:
    label: 'SvgStore'
    parent: sourceopt

settings:
  sourceopt.enabled:
    category: sourceopt.cleaner
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:sourceopt.enabled
    type: bool
    default: true
  sourceopt.removeGenerator:
    category: sourceopt.cleaner
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:sourceopt.removeGenerator
    type: bool
    default: true
  sourceopt.removeComments:
    category: sourceopt.cleaner
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:sourceopt.removeComments
    type: bool
    default: true
  sourceopt.keepComments:
    category: sourceopt.cleaner
    label: 'Spare these listed comments [RegEx]'
    type: stringlist
    default:
      - '/^TYPO3SEARCH_/usi'
  sourceopt.headerComment:
    category: sourceopt.cleaner
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:sourceopt.headerComment
    type: string
    default: ''
  sourceopt.formatHtml.enabled:
    category: sourceopt.formater
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:sourceopt.formatHtml
    type: bool
    default: true
  sourceopt.formatHtml.tabSize:
    category: sourceopt.formater
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:sourceopt.formatHtmlTabSize
    type: int
    default: 4
  sourceopt.formatHtml.indentation:
    category: sourceopt.formater
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:sourceopt.formatHtmlIndentation
    type: int
    default: 2
  sourceopt.formatHtml.debugComment:
    category: sourceopt.formater
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:sourceopt.formatHtmlDebugComment
    default: false
    type: bool
  svgstore.enabled:
    category: sourceopt.svgstore
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:svgstore.enabled
    type: bool
    default: true
  svgstore.renderMode:
    category: sourceopt.svgstore
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:svgstore.renderMode
    type: select
    default: symbol
  items:
    - label: 'Reference all SVGs (default)'
      value: symbol
    - label: 'Inline single-use SVGs (optimize traffic)'
      value: distinct
    - label: 'Inline all SVGs at HTML (not recommended)'
      value: inline
  svgstore.fileSize:
    category: sourceopt.svgstore
    label: LLL:EXT:sourceopt/Resources/Private/Language/locallang.xlf:svgstore.fileSize
    type: int
    default: 50000
